# Welcome to Jekyll!

# Website settings
title: "AmJ"
description: "Personal page using Jack's JalPC Jekyll theme"
keywords: "Ashutosh,AmJ,Profile, Blog,Jekyll,github,gh-page"
baseurl: "/homepage/"

url: "https://ashutoshmjain.github.io/homepage/"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'AmJ'
  first_name: 'Ashutosh'
  last_name: 'Jain'
  email: 'amj@smbstack.com'
  facebook_username: 'ashutoshmjain'
  github_username: 'ashutoshmjain'
  twitter_username: 'ashutoshmjain'
  avatar: 'static/img/landing/profilepic.png'
  desc: 'FOSS enthusiast| regular blogger | daily runner | Bernie fan | Trying (and failing :-) to live a minimal life'
# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: 'ashutoshmjain'
  public_key: V5TjtTXz8HPCSeL0tuAa6Lw8DOcsmzKAOw5kVjn2cVtBggntGPpjZ4YlMMHmS1P1

# share
#bshare:
        #uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
#ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
        id: UA-90523130-1

# growingIO
gio:
        #id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
